from pydantic import BaseModel, ConfigDict

from integration.model.sub_model import SubModelId
from integration.plan.plan import InferencePlanVersion, SubModelDeployment
from worker.domain.model_pass.model_pass_context import (
    ModelPassContext,
)
from worker.domain.sub_model.invocation.sub_model_invocation_context import (
    SubModelInvocationContext,
)
from worker.domain.tensor.tensor import TensorBundle


## An invocation message is identified by:
## - The context of the invoker
## - The deployment-id of the sub model we are invoking
class SubModelInvocationMessageContext(BaseModel):
    model_config = ConfigDict(frozen=True)
    model_pass_context: ModelPassContext
    source_sub_model_invocation_context: SubModelInvocationContext | None
    sub_model_deployment_id: SubModelDeployment


## This is the input to the execution of a successor as generated by a predecessor
class SubModelInvocationMessage(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: SubModelInvocationMessageContext
    payload: TensorBundle

    @property
    def plan_version(self) -> InferencePlanVersion:
        return self.context.model_pass_context.plan_version

    @property
    def sub_model_id(self) -> SubModelId:
        return self.context.sub_model_deployment_id.sub_model_id

    @property
    def model_pass_context(self) -> ModelPassContext:
        return self.context.model_pass_context

    @property
    def sub_model_deployment_id(self) -> SubModelDeployment:
        return self.context.sub_model_deployment_id


## This is the ack for the reception of a SubModelInferenceMessage
class SubModelInvocationAck(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: SubModelInvocationMessageContext
