from worker.application.ports.outbound.service_inference_plan_store import (
    ServiceInferencePlanStore,
)
from worker.domain.sub_model.invocation.sub_model_invocation_context import (
    SubModelInvocationContext,
    SubModelInvocationId,
)
from worker.domain.sub_model.invocation.sub_model_invocation_message import (
    SubModelInvocationMessage,
)
from worker.domain.sub_model.invocation.sub_model_invocation_request_response import (
    SubModelInvocationRequest,
)
from worker.domain.tensor.tensor import TensorBundle


class SubModelInvocationRequestBuilder:
    def __init__(self, plan_store: ServiceInferencePlanStore):
        super().__init__()
        self._plan_store = plan_store

    ## The sub-model invocation request is the input to the sub-model execution
    ## The tensor bundle carries only the inputs of the sub-model, not the skip tensors
    ## This is the input of the sub-model as produced by the sub-model invocation message gatherer
    ## Which means that it carries only tensors that are generated by previous sub-model invocations
    async def build_sub_model_invocation_request(
        self,
        all_sub_model_invocation_messages: list[SubModelInvocationMessage],
        sub_model_invocation_id: SubModelInvocationId,
    ) -> SubModelInvocationRequest:

        plan = await self._plan_store.get_service_inference_plan_by_version(
            all_sub_model_invocation_messages[0].plan_version
        )
        if plan is None:
            raise ValueError(
                f"Service inference plan for version {all_sub_model_invocation_messages[0].plan_version} not found"
            )

        sub_model_id = all_sub_model_invocation_messages[0].sub_model_id
        execution_scheme = plan.sub_model_execution_schemes[sub_model_id]

        full_payload = TensorBundle(bundle={})
        for msg in all_sub_model_invocation_messages:
            full_payload = full_payload.merge(
                msg.payload.filter(execution_scheme.inputs)
            )

        model_pass_context = all_sub_model_invocation_messages[0].model_pass_context
        sub_model_deployment_id = all_sub_model_invocation_messages[
            0
        ].sub_model_deployment_id

        return SubModelInvocationRequest(
            context=SubModelInvocationContext(
                model_pass_context=model_pass_context,
                sub_model_deployment_id=sub_model_deployment_id,
                sub_model_invocation_id=sub_model_invocation_id,
            ),
            payload=full_payload,
        )
