from pydantic import BaseModel, ConfigDict


## This is the input of the sub-model once everything for the sub-model has been gathered from predecessors
class InferenceRequest(BaseModel):
    model_config = ConfigDict(frozen=True)
    pass


## This is the output of the sub-model once everything for the sub-model has been gathered from predecessors
class InferenceResponse(BaseModel):
    model_config = ConfigDict(frozen=True)
    pass


## This is the input to the execution of a successor as generated by a predecessor
class InferenceMessage(BaseModel):
    model_config = ConfigDict(frozen=True)
    pass
