from pydantic import BaseModel, ConfigDict

from shared.model.model_partition import ModelPartitionId
from shared.plan.plan import InferencePlanVersion, PartitionDeployment
from worker.domain.context.model_pass_context import (
    ModelPassContext,
)
from worker.domain.context.partition_invocation_context import (
    PartitionInvocationContext,
)
from worker.domain.partition.tensor_bundle import TensorBundle


## A partition invocation contribution is identified by:
## - The context of the invoker
## - The deployment-id of the sub model we are invoking
class PartitionInvocationContributionContext(BaseModel):
    model_config = ConfigDict(frozen=True)
    model_pass_context: ModelPassContext
    source_partition_invocation_context: PartitionInvocationContext | None
    partition_deployment_id: PartitionDeployment


## This is the input to the execution of a successor as generated by a predecessor
class PartitionInvocationContribution(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: PartitionInvocationContributionContext
    bundle: TensorBundle

    @property
    def plan_version(self) -> InferencePlanVersion:
        return self.context.model_pass_context.plan_version

    @property
    def partition_id(self) -> ModelPartitionId:
        return self.context.partition_deployment_id.partition_id

    @property
    def model_pass_context(self) -> ModelPassContext:
        return self.context.model_pass_context

    @property
    def partition_deployment(self) -> PartitionDeployment:
        return self.context.partition_deployment_id


## Acknowledges receipt of a partition invocation contribution.
class PartitionInvocationContributionAck(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: PartitionInvocationContributionContext
