from pydantic import BaseModel, ConfigDict

from shared.context.ingress_invocation_context import IngressInvocationContext
from shared.context.model_pass_context import (
    ModelPassContext,
)
from shared.model.model_partition import ModelPartitionId
from shared.plan.partition_replica_id import PartitionReplicaId
from shared.plan.plan_version import PlanVersion
from shared.tensor.tensor_bundle import TensorBundle
from worker.domain.context.partition_invocation_context import (
    PartitionInvocationContext,
)

type SourceInvocationContext = PartitionInvocationContext | IngressInvocationContext


## This is the input to the execution of a successor as generated by a predecessor
class PartitionInvocationContribution(BaseModel):
    model_config = ConfigDict(frozen=True)

    source_invocation_context: SourceInvocationContext
    target_replica_id: PartitionReplicaId
    bundle: TensorBundle

    @property
    def plan_version(self) -> PlanVersion:
        return self.source_invocation_context.model_pass_context.plan_version

    @property
    def partition_id(self) -> ModelPartitionId:
        return self.target_replica_id.partition_id

    @property
    def model_pass_context(self) -> ModelPassContext:
        return self.source_invocation_context.model_pass_context

    @property
    def source_replica_id(self) -> PartitionReplicaId | None:
        if isinstance(
            self.source_invocation_context,
            PartitionInvocationContext,
        ):
            return self.source_invocation_context.partition_replica_id

        return None


## Acknowledges receipt of a partition invocation contribution.
class PartitionInvocationContributionAck(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: SourceInvocationContext
