from pydantic import BaseModel, ConfigDict

from distributed_inference.domain.plan import InferencePlanVersion
from distributed_inference.model_manager.domain.sub_model import SubModelDeploymentId
from distributed_inference.worker.domain.model_pass.model_pass_context import (
    ModelPassContext,
)
from distributed_inference.worker.domain.sub_model.invocation.sub_model_invocation_context import (
    SubModelInvocationContext,
)
from distributed_inference.worker.domain.tensor.tensor import TensorBundle


## An invocation message is identified by:
## - The context of the invoker
## - The deployment-id of the sub model we are invoking
class SubModelInvocationMessageContext(BaseModel):
    model_config = ConfigDict(frozen=True)
    model_pass_context: ModelPassContext
    source_sub_model_invocation_context: SubModelInvocationContext | None
    sub_model_deployment_id: SubModelDeploymentId


## This is the input to the execution of a successor as generated by a predecessor
class SubModelInvocationMessage(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: SubModelInvocationMessageContext
    payload: TensorBundle

    def get_plan_version(self) -> InferencePlanVersion:
        return self.context.model_pass_context.plan_version


## This is the ack for the reception of a SubModelInferenceMessage
class SubModelInvocationAck(BaseModel):
    model_config = ConfigDict(frozen=True)

    context: SubModelInvocationMessageContext
