from pydantic import BaseModel, ConfigDict


## This is the input to the execution of a successor as generated by a predecessor
class SubModelInferenceMessage(BaseModel):
    model_config = ConfigDict(frozen=True)
    pass


## This is the ack for the reception of a SubModelInferenceMessage
class SubModelInferenceMessageAck(BaseModel):
    model_config = ConfigDict(frozen=True)
    pass
